### ISSUE TITLE
What is this Greenkeeper Bot ruckus all about? 

### ISSUE THREAD

**Issue by ryanwiemer** [chrisheninger/rental-resume.com#40]
Yo @chrisheninger, 

Just curious about this Greenkeeper bot thing. What is it intended to do? Is this something you are just trying out or do you intend to make it a permanent workflow for this project?

Thanks,
Ryan

**Comment by chrisheninger** [comment]
Yeeeeeeeah, whoops! Was trying it out as a way to get all the project dependencies up-to-date... but I forgot about it and haven't checked my notifications in a while. I'll remove it later.

**Comment by ryanwiemer** [comment]
Haha no problem. It looks interesting but properly a little overkill for the purposes of this project. Unless you want like 5 PRs a day related to minor version bumps of dependencies. ;)

**Comment by chrisheninger** [comment]
Killed it.
