### ISSUE TITLE
Update all-the-things

### ISSUE THREAD

**Issue by chrisheninger** [chrisheninger/rental-resume.com#56]
I'm gonna get this repo updated with all the latest and greatest in the React world.
- [x] Use Create-React-App so we don't have to maintain configs
- [x] `prettier` and husky/lint-staged for pre-commit hooks
- [x] Update react to latest and add `prop-types`
- [x] Move hosting from surge to gh-pages
- [x] Set up Cloudflare for free https and CDN
- [x] Offline capability thanks to `react-scripts`
- [x] Use [Icon Magic](https://github.com/chrisheninger/icon-magic) to create add-to-homescreen icons
- [x] Start improving things from Lighthouse checklist https://developers.google.com/web/tools/lighthouse/

**Comment by chrisheninger** [comment]
I've started this here: https://github.com/chrisheninger/rental-resume.com/commits/v3

**Comment by ryanwiemer** [comment]
Rock on @chrisheninger! I have been meaning to get back to this project. I think you might have merged in some changes I did several months ago for the "optional sections" but just an FYI those were incomplete. lol.

One more idea for the check list. I think it would be cool to add the ability to sort sections on the preview page. Perhaps using something like this: http://clauderic.github.io/react-sortable-hoc/#/basic-configuration/basic-usage?_k=lden9b

Just an idea.

**Comment by chrisheninger** [comment]
I'd recommend this one: http://react-dnd.github.io/react-dnd/examples-sortable-simple.html

Feel free to give it a go on the `v3` branch. To get it running, it should just be a matter of deleting your node_modules folder and re-running `npm install` and then `npm start`.

We can chat sometime soon.. I'd love to get this thing updated (since it's been ~a year) and really polished so we can promote it and hopefully help some people!

**Comment by chrisheninger** [comment]
@ryanwiemer Go ahead and create a new issue regarding ☝️, I'm gonna close this one– everything is complete.

https :D :D :D

https://rental-resume.com/

**Comment by ryanwiemer** [comment]
@chrisheninger, dude you rock! Great work. Sounds good regarding a new issue for the sorting functionality.
