### ISSUE TITLE
Section Inputs Not Working Correctly after Adding New Sections

### ISSUE THREAD

**Issue by ryanwiemer** [chrisheninger/rental-resume.com#66]
@chrisheninger, 

![add new sections bug](https://user-images.githubusercontent.com/5171579/27353103-bc15227a-55b7-11e7-8826-45a78b3586d4.gif)

I noticed this new bug when working on another item the other day. I believe this was introduced at some point when you added this fix (#60). 

**Steps to Replicate Issue**
- Navigate to https://rental-resume.com/applicant
- Click on "Add Another Person" at least two times. 
- Enter in information on any of the inputs on the sections after the first one. 
- Notice that updating the inputs is duplicated in all of the sections after the first. 
- Note this bug is an issue on pages where the user has the ability to add new people, employment history records, or rental history records.

**Comment by chrisheninger** [comment]
Whoops, I'll get this fixed up. 👍

**Comment by chrisheninger** [comment]
Fixed here: https://github.com/chrisheninger/rental-resume.com/commit/40f8fedbeff779ebda691c67209aca4bb6eea04d
